---
title: "Compare SPCC 1.0 & 1.3d - Palm Beach County"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r, include = FALSE, echo = FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

require(tidyverse)
require(sf)
#library(arcgisbinding)
library(raster)
library(tmap)
library(kableExtra)
library(osmdata)

options(width = 2000)

epsg <- 2236

tmap_mode("view")

#arc.check_product()

options(scipen=999)
```

```{r}
#SPCC colors

spcc_palette <- c("#267300", '#D7C29E', "#FFFFD4", "#F5EE1C", "#FFBEBE", "#E60000", "#730000", "#89CD66", "#828282", "#AA66CD", "#004C73", "#00C5FF")

boundary <- st_read("K:/Projects/D4_CSHnetwork/Features/LU/SPCC_20/data_prep/cleaned_data/study_area/study_area.shp", quiet = TRUE) %>% 
  st_transform(epsg)

template<-raster(boundary, res=500)

```


```{r}
#function to obtain bounding box in format needed by dodgr

study_area_bbox_function = function(study_area){
  sa = st_read(study_area,
               quiet = TRUE) %>%
    st_transform(4326)
  sa_bb = st_bbox(sa)
  buffer_bb = matrix(c(sa_bb["xmin"],
                       sa_bb["ymin"],
                       sa_bb["xmax"],
                       sa_bb["ymax"]),
                     nrow = 2,
                     ncol = 2,
                     dimnames = list(c("x","y"), c("min","max")))
  return(buffer_bb)
}


study_area_bbox <- study_area_bbox_function("K:/Projects/D4_CSHnetwork/Features/LU/SPCC_20/data_prep/cleaned_data/study_area/study_area.shp")
```


```{r}

osm_townhall <- opq(bbox = study_area_bbox) %>%
      add_osm_feature(key = 'amenity', value = "townhall") %>% 
  osmdata_sf()

osm_townhall$osm_points$type <- "townhall"
osm_townhall$osm_polygons$type <- "townhall"

osm_postoffice <- opq(bbox = study_area_bbox) %>%
      add_osm_feature(key = 'amenity', value = "post_office") %>% 
  osmdata_sf()

osm_postoffice$osm_points$type <- "postoffice"
osm_postoffice$osm_polygons$type <- "postoffice"

osm_police <- opq(bbox = study_area_bbox) %>%
      add_osm_feature(key = 'amenity', value = "police") %>% 
  osmdata_sf()

osm_police$osm_points$type <- "police"
osm_police$osm_polygons$type <- "police"

osm_fire <- opq(bbox = study_area_bbox) %>%
      add_osm_feature(key = 'amenity', value = "fire_station") %>% 
  osmdata_sf()

osm_fire$osm_points$type <- "fire"
osm_fire$osm_polygons$type <- "fire"

osm_courthouse <- opq(bbox = study_area_bbox) %>%
      add_osm_feature(key = 'amenity', value = "courthouse") %>% 
  osmdata_sf()

osm_courthouse$osm_points$type <- "courthouse"
osm_courthouse$osm_polygons$type <- "courthouse"

osm_library <- opq(bbox = study_area_bbox) %>%
      add_osm_feature(key = 'amenity', value = "library") %>% 
  osmdata_sf()

osm_library$osm_points$type <- "library"
osm_library$osm_polygons$type <- "library"

osm_government <- opq(bbox = study_area_bbox) %>%
      add_osm_feature(key = 'office', value = "government") %>% 
  osmdata_sf()

osm_government$osm_points$type <- "government"
osm_government$osm_polygons$type <- "government"

merged_points <- bind_rows(osm_townhall$osm_points,
                            st_centroid(osm_townhall$osm_polygons),
                            osm_postoffice$osm_points,
                            st_centroid(osm_postoffice$osm_polygons),
                            osm_police$osm_points,
                            st_centroid(osm_police$osm_polygons),
                            osm_fire$osm_points,
                            st_centroid(osm_fire$osm_polygons),
                            osm_courthouse$osm_points,
                            st_centroid(osm_courthouse$osm_polygons),
                            osm_library$osm_points,
                            st_centroid(osm_library$osm_polygons),
                            osm_government$osm_points,
                            st_centroid(osm_government$osm_polygons)) %>% 
  dplyr::select(name, type) %>% 
  st_transform(epsg)

saveRDS(merged_points, "K:/Projects/D4_CSHnetwork/Features/LU/SPCC_20/data_prep/demo_data/services_count_overlay/services_merged_points.rds")

```

```{r}

tm_shape(merged_points) + tm_dots(col = "type")

```


#summarize by grid cells

```{r}

#make grids

grid <- st_make_grid(boundary, 500) %>% 
  st_as_sf() %>% 
  mutate(gridID = row_number())

grid_buffer_filtered <- grid %>% 
  st_buffer(500) %>% 
  st_filter(merged_points, .predicate = st_intersects)

grid_subset <- grid %>% 
  st_filter(grid_buffer_filtered, .predicate = st_intersects)

#summarize to buffered grid, associate back to regular grid

buffered_grid_with_points <- st_join(grid_buffer_filtered,
          dplyr::select(merged_points, type))

counts_by_cell <- buffered_grid_with_points %>% 
  st_drop_geometry() %>% 
  group_by(gridID) %>% 
  summarise(count = n_distinct(type))

grid_with_summary <- left_join(grid_subset, counts_by_cell) %>% 
  drop_na(count)

saveRDS(grid_with_summary, "K:/Projects/D4_CSHnetwork/Features/LU/SPCC_20/data_prep/demo_data/services_count_overlay/services_count_grid.rds")


```



```{r}

gov_raster <-rasterize(merged_government, template, field = "count",
                           fun='count', background=0)

gov_raster_quarter <- focal(gov_raster, w=matrix(1,nrow=3,ncol=3), fun=mean)

tm_shape(gov_raster_quarter) + tm_raster(style = "fixed", 
                                             breaks = c(1, 2, 4, 6, 8, 10, 50),
                                             palette = "viridis")



```

